#!/bin/bash
DIR="/home/$USER/clab/lab1&2"
start="#include <stdio.h> \n
#define WriteLine() printf(\"\\\n\"); \n
#define WriteLong(x) printf(\" %lld\", (long)x); \n
#define ReadLong(a) if (fscanf(stdin, \"%lld\", &a) != 1) a = 0; \n
#define long long long"

report(){
if [ ${6}x != -1x ]
then echo "$DIR/examples/$5.c"
else echo "$DIR/sample/$5.c"
fi
if [ $1 = $3 ]
then 
echo "Decompile Test > Test Passed!"
echo
else 
echo "Decompile Test > Test Failed!"
echo
fi
}

if [ ${3}x = -sx ]
then
echo "Decompile to final C file $1"
if [ ${4}x != -1x ]

then
awk "{print}" $DIR/mid/$2.mid2 > $DIR/mid/$2.midc
awk "{print}" $DIR/mid/$2.mid2 >> $DIR/mid/$2.midc
rm $DIR/mid/$2.mid2
echo -e $start > $DIR/finalc/${2}_decp.c
$DIR/bin/decp < $DIR/mid/$2.midc >> $DIR/finalc/${2}_decp.c
echo "Compile the C files and check the output!"
gcc $DIR/finalc/${2}_decp.c -o $DIR/elf/tg/$2
gcc $DIR/examples/$2.c -o $DIR/elf/sc/$2
$DIR/elf/tg/$2 > $DIR/temptg
$DIR/elf/sc/$2 > $DIR/tempsc
report `md5sum $DIR/temptg $DIR/tempsc` $2 >> $DIR/reports/report1.txt
rm $DIR/temptg
rm $DIR/tempsc

else
awk "{print}" $DIR/sample/mid2 > $DIR/sample/midc
awk "{print}" $DIR/sample/mid2 >> $DIR/sample/midc
rm $DIR/sample/mid2
echo -e $start > $DIR/sample/finalc.c
$DIR/bin/decp < $1 >> $DIR/sample/finalc.c
echo "Compile the C files and check the output!"
gcc $DIR/sample/finalc.c -o $DIR/sample/${2}_decp
gcc $DIR/sample/$2.c -o $DIR/sample/$2
$DIR/sample/${2}_decp > $DIR/temptg
$DIR/sample/$2 > $DIR/tempsc
report `md5sum $DIR/temptg $DIR/tempsc` $2 -1 >> $DIR/reports/report1.txt
rm $DIR/temptg
rm $DIR/tempsc

fi
fi
